// src/app/components/user-info-box/user-info-box.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'user-info-box',
  templateUrl: './user-info-box.component.html',
  styleUrls: ['./user-info-box.component.css']
})
export class UserInfoBoxComponent implements OnInit {
    user = {
        displayName: 'Harrmalik',
        userName: 'Malik Harrison',
        avatar: 'http://lorempixel.com/100/100/people/8/',
        posts: [],
        following: 1,
        followers: 0
    }
  constructor() { }

  ngOnInit() {
  }

}

<div class="ui segment stacked blue">
  <h3 class="ui header">
     <img src="{{user.avatar}}" class="ui image tiny floated left">
     <a href="/#/user/{{user.displayName}}">{{user.displayName}}</a>
  </h3>
  <br><br>
  <br>
   <div class="ui mini statistic floated">
     <div class="label">
       Posts
     </div>
     <div class="value">
       {{user.posts.length}}
     </div>
   </div>
   <div class="ui mini statistic floated">
     <div class="label">
      Following
     </div>
     <div class="value">
      {{user.following}}
     </div>
   </div>
   <div class="ui mini statistic floated">
     <div class="label">
      Followers
     </div>
     <div class="value">
      {{user.followers}}
     </div>
   </div>
</div>

// React/components/UserInfoBox.js
import React from 'react'

var UserInfoBox = React.createClass({
  render() {
    return (
      <article className="four wide column">
        <div className="ui segment stacked blue">
        <h3 className="ui header">
           <img src="http://lorempixel.com/100/100/people/8/" className="ui image tiny floated left avatar"></img>
           <a href="/#/user/{{user.displayName}}">BestCoderNA</a>
        </h3>
         <div className="ui mini statistic floated">
           <div className="label">
             Posts
           </div>
           <div className="value">
             2
           </div>
         </div>
         <div className="ui mini statistic floated">
           <div className="label">
            Following
           </div>
           <div className="value">
            0
           </div>
         </div>
         <div className="ui mini statistic floated">
           <div className="label">
            Followers
           </div>
           <div className="value">
            0
           </div>
         </div>
      </div>
      </article>
    )
  }
})

export default UserInfoBox
