// React/components/ChatFeed.js
import React from 'react'

var ChatFeed = React.createClass({
  render() {
    return (
      <article className="eight wide column">
        <form className="ui form fluid segment stacked blue">
          <div className="required field">
             <h4>Harrmalik says</h4>
          </div>
          <div className="field">
            <div className="ui icon input">
              <input required type="text" placeholder="Whats on your mind?" />
              <i className="chat icon"></i>
            </div>
          </div>
          <input className="ui button blue right floated" type="submit" value="Send" id="send" />
        </form>

        <h3 className="ui blue header"><i className="ui chat icon"></i>Chat Feed</h3>
        <div className="ui divider"></div>

        <div className="ui feed message">
          <div className="event">
              <div className="label">
                <img src="http://lorempixel.com/100/100/people/8/"></img>
              </div>
              <div className="content">
                  <div className="summary">
                      <a className="user">
                          Malik Harrison
                      </a>
                      <div className="date">
                          @Harrmalik 34m ago
                      </div>

                  </div>
                  <div className="extra text">
                      This is sample text
                  </div>

                  <div className="meta">
                      <a className="reply">
                          <i className="reply icon"></i> 1 Replies
                      </a>

                      <a className="retweet">
                          <i className="retweet icon"></i> 2 Reposts
                      </a>

                      <a className="like">
                          <i className="like icon"></i> 3 Likes
                      </a>
                  </div>
              </div>
          </div>
        </div>
      </article>
    )
  }
})

export default ChatFeed

// src/app/components/chat-feed/chat-feed.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'chat-feed',
  templateUrl: './chat-feed.component.html',
  styleUrls: ['./chat-feed.component.css']
})
export class ChatFeedComponent implements OnInit {
    posts = [{
        profileImage: 'http://lorempixel.com/100/100/people/8/',
        createdBy: 'Malik Harrison',
        displayName: 'Harrmalik',
        createdAt: "34m ago",
        displayText: "This is sample text",
        replies: 1,
        reposts: 2,
        likes: 3
    },{
        profileImage: 'http://lorempixel.com/100/100/people/7/',
        createdBy: 'Malik Harrison',
        displayName: 'Harrmalik',
        createdAt: "34m ago",
        displayText: "This is sample text",
        replies: 1,
        reposts: 2,
        likes: 3
    },{
        profileImage: 'http://lorempixel.com/100/100/people/9/',
        createdBy: 'Malik Harrison',
        displayName: 'Harrmalik',
        createdAt: "34m ago",
        displayText: "This is sample text",
        replies: 1,
        reposts: 2,
        likes: 3
    }]

    constructor() { }

    ngOnInit() {
    }

}

<h3 class="ui blue header"><i class="ui chat icon"></i>Chat Feed</h3>
<div class="ui divider"></div>

<div class="ui feed message" *ngFor="let post of posts" ng-class-odd="'floating teal'" ng-class-even="''">
    <div class="event">
        <div class="label">
          <img src="{{post.profileImage}}">
        </div>
        <div class="content">
            <div class="summary">
                <a class="user">
                    {{post.createdBy}}
                </a>
                <div class="date">
                    @{{post.displayName}} {{post.createdAt}}
                </div>

            </div>
            <div class="extra text">
                {{post.displayText}}
            </div>

            <div class="meta">
                <a class="reply">
                    <i class="reply icon"></i> {{post.replies}} Replies
                </a>

                <a class="retweet">
                    <i class="retweet icon"></i> {{post.reposts}} Reposts
                </a>

                <a class="like">
                    <i class="like icon"></i> {{post.likes}} Likes
                </a>
            </div>
        </div>
    </div>
</div>

<!-- <div class="ui feed message" ng-repeat="post in posts | filter:search | orderBy:'created_at':true" ng-class-odd="'floating teal'" ng-class-even="''">
    <div class="event">
        <div class="content">
            <div class="summary">
                <a class="user" ng-click="friendPage(post.user_id)">
                {{post.created_by}}
                </a>
                <div class="date">
                {{(post.created_at) | date:"h:mma 'on' MMM d, y"}}
                </div>
                <div ng-if="editingPost === post" style="display: inline-block; float: right;" ng-click="cancel(post)">
                <i class="remove icon" style="margin:0px;"></i>
                </div>
                <br>
                <div ng-if="post.user_id !== currUserId">
                    <a ng-if="checkFollows(post.user_id)" ng-click="followUser(post.user_id)">Follow {{post.created_by}}</a>
                    <a ng-if="!checkFollows(post.user_id)" ng-click="unfollowUser(post.user_id)">Unfollow {{post.created_by}}</a>
                    <br>
                </div>

                <div ng-if="editingPost !== post" ng-bind-html="post.displayText"></div>

                <div ng-if="editingPost === post">
                    <div class="ui form">
                        <div class="field">
                        <textarea rows="2" ng-model="post.text"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div ng-if="post.user_id === currUserId" style="margin-top: 5px;">
                <button class="mini ui blue button" ng-if="editingPost !== post" ng-click="edit(post)">Edit</button>
                <button class="mini ui green button" ng-if="editingPost === post" ng-click="save(post)">Save</button>
                <button class="mini ui red button" ng-click="delete(post)">Delete</button>
            </div>
        </div>
    </div>
</div> -->
